spring:
  kafka:
    producer:
      client-id: json-pos-simulator
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

kafka-pos-simulator:
  pos-topic: pos_topic
  pos-topic-replicas: 1
  pos-topic-partitions: 1
